### ISSUE TITLE
Uploader - Mac

### ISSUE THREAD

**Issue by GaryinaBox** [xinabox/XinaBoxUploader#3]
Deleted previous version of Uploader.
Downloaded file from Github and put it in the applications folder as normal.
Clicked on icon in applications file to run the uploader - iOS said the file was old and couldn't run. 
Reverted to older version of Uploader.

**Comment by gotfredsen** [comment]
Gary, please check out this video and see if it helps: https://youtu.be/UIEQnG2oMEI

**Comment by GaryinaBox** [comment]
Thanks Bjarke,
I didn’t know about going into System Preferences > Security
It works now.
